# Generated by Django 4.0.4 on 2022-05-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=50)),
                ('creditosMateria', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
