# Generated by Django 4.0.4 on 2022-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='horasMateria',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
