# Generated by Django 4.0.4 on 2022-05-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0002_materia_horasmateria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='horasMateria',
        ),
    ]
