# Generated by Django 4.0.4 on 2022-05-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0003_remove_materia_horasmateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('idAlumno', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreAlumno', models.CharField(max_length=50)),
                ('apellidoAlumno', models.CharField(max_length=50)),
                ('grupoAlumno', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('idDocente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreDocente', models.CharField(max_length=50)),
                ('apellidoDocente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idGrupo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombreGrupo', models.CharField(max_length=50)),
                ('idDocente', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGrupo', models.PositiveSmallIntegerField()),
                ('idAlumno', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrupoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGrupo', models.PositiveSmallIntegerField()),
                ('idMateria', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
