# Generated by Django 4.0.4 on 2022-05-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0004_alumno_docente_grupo_grupoalumno_grupomateria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoalumno',
            name='idAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.alumno'),
        ),
        migrations.AlterField(
            model_name='grupoalumno',
            name='idGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.grupo'),
        ),
        migrations.AlterField(
            model_name='grupomateria',
            name='idGrupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.grupo'),
        ),
        migrations.AlterField(
            model_name='grupomateria',
            name='idMateria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.materia'),
        ),
    ]
