# Generated by Django 4.0.4 on 2022-05-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0006_alter_alumno_grupoalumno_alter_grupo_iddocente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='idDocente',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Horario.docente'),
        ),
    ]
