# Generated by Django 4.0.4 on 2022-05-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0007_alter_grupo_iddocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='grupoAlumno',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idDocente',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
