# Generated by Django 4.0.4 on 2022-05-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0008_alter_alumno_grupoalumno_alter_grupo_iddocente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='idDocente',
        ),
    ]
