# Generated by Django 4.0.4 on 2022-05-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0009_remove_grupo_iddocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='idDocente',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
