# Generated by Django 4.0.4 on 2022-05-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0011_alter_alumno_grupoalumno_alter_grupo_iddocente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='idDocente',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Horario.docente', unique=True),
        ),
    ]
